name: Flutter CI/CD

# Trigger the workflow on push and pull request events
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'

    # Step 3: Install dependencies
    - name: Get dependencies
      run: flutter pub get

    # Step 4: Run tests
    - name: Run tests
      run: flutter test
    
    # Step 5: Build Android debug APK
    - name: Build APK
      run: flutter build apk --debug
    